In [1]:
# 匯入必要的庫
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# 生成一些示範數據
# 我們這裡使用Scikit-Learn內建的Iris數據集
from sklearn.datasets import load_iris

# 載入數據集
data = load_iris()
X = data.data  # 特徵
y = data.target  # 標籤

# 將數據集分割為訓練集和測試集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 初始化KNN分類器，這裡設置k值為3
knn = KNeighborsClassifier(n_neighbors=3)

# 使用訓練數據來訓練模型
knn.fit(X_train, y_train)

# 使用測試數據進行預測
y_pred = knn.predict(X_test)

# 評估模型的準確性
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# 打印分類報告和混淆矩陣
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 1.00
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
